version: "3"
services:
  myblog-frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./Client
    volumes:
      - /myblog/node_modules
      - ./Client:/myblog
    stdin_open: true
    environment: 
     - CHOKIDAR_USEPOLLING=true
  myblog-nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
  myblog-backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: myblog_backend
    volumes:
      - /myblog/node_modules
      - ./server:/myblog
    environment: 
      # MYSQL_HOST: myblog-mysql
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myblog
      MYSQL_PORT: 3306
    #   NODE_ENV: development
    # environment:  
    #  - CHOKIDAR_USEPOLLING=true  

# # Local port 3310
#   myblog-mysql:
#     build: ./mysql
#     restart: unless-stopped
#     container_name: myblog_mysql
#     ports:
#       - "3310:3306"
#     volumes:
#       - ./mysql/mysql_data:/var/lib/mysql
#       - ./mysql/sqls/:/docker-entrypoint-initdb.d/
#     environment:
#       MYSQL_HOST: myblog-mysql
#       MYSQL_USER: root
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: myblog
